apiVersion: v1
kind: Secret
metadata:
  name: municipal-secret
  namespace: municipal

type: Opaque

stringData:
  SECRET_KEY: "supersecretkey"

  DATABASE_URL: "postgresql://postgres:Chula123!@municipal-postgres.cjqgwiy282it.ap-south-1.rds.amazonaws.com:5432/complaints_db"

  BUCKET_NAME: "your-s3-bucket-complain"

  SNS_TOPIC_ARN: "arn:aws:sns:ap-south-1:051826716700:demo"

  AWS_REGION: "ap-south-1"