version: "3.9"

services:
  web:
    image: 051826716700.dkr.ecr.ap-south-1.amazonaws.com/complain-system:latest
    container_name: complaint-system
    restart: always
    ports:
      - "5000:5000"

    env_file:
     - .env

    volumes:
      - ./static/uploads:/app/static/uploads

    environment:
      DB_HOST: municipal-postgres.cjqgwiy282it.ap-south-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: complaints_db
      DB_USER: postgres
      DB_PASSWORD: Chula123!
      FLASK_ENV: production

volumes:
  uploads:
